/**
 * Generated Route Tree
 * 
 * This file is auto-generated by @tanstack/router-plugin
 * DO NOT EDIT MANUALLY
 * 
 * Run `npm run dev` to regenerate this file based on src/routes/
 */

// Placeholder - will be generated by TanStack Router plugin
export const routeTree = {} as any
